name: Guatemala_env
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - r-base=4.2.2
  - r-janitor
  - r-tidyverse
  - r-remotes
  - r-usethis
  - r-REDcapR
  - r-ggplot2
  - r-lubridate
  - r-purrr
  - r-ggrepel
  - r-dplyr
  - r-shiny
  - r-bslib