name: Update data weekly Monday 9am EST

on:
  schedule:
    - cron: "0 13 * * 1"
  push:
    branches: [ main ]

jobs:
  run_update_data:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: .github/Guatemala_env.yml
          environment-name: Guatemala_env
      - name: Run R file
        env:
          influenza_token: ${{ secrets.INFLUENZA_TOKEN }}
          namru_biofire_token: ${{ secrets.NAMRU_BIOFIRE_TOKEN }}
          agri_casa_token: ${{ secrets.AGRI_CASA_TOKEN }}
          r_shiny_account_token: ${{ secrets.R_SHINY_ACCOUNT_TOKEN }}
        run: |
          Rscript code/redcap_data_processing.R
          Rscript code/deploy_app.R