name: Weekly Data Update and Deployment

on:
  schedule:
    - cron: "0 13 * * 1"
  push:
    branches: [ main ]

jobs:
  run_update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MicroMamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: .github/Guatemala_env.yml
          environment-name: Guatemala_env

      - name: Run R scripts
        env:
          influenza_token: ${{ secrets.INFLUENZA_TOKEN }}
          namru_biofire_token: ${{ secrets.NAMRU_BIOFIRE_TOKEN }}
          agri_casa_token: ${{ secrets.AGRI_CASA_TOKEN }}
          r_shiny_account_token: ${{ secrets.R_SHINY_ACCOUNT_TOKEN }}
        run: |
          Rscript code/redcap_data_processing.R
          
          # Check if there are changes in agri_casa_summary.csv or influenza_summary.csv
          if ! git diff --quiet --exit-code docs/agri_casa_summary_updated.csv \
           || ! git diff --quiet --exit-code docs/influenza_summary_updated.csv; then
            git config --local user.name "GitHub Actions"
            git config --local user.email "actions@github.com"

            timestamp=$(date +'%Y%m%d%H%M%S')
            branch_name="update-csv-$timestamp"

            git checkout -b "$branch_name"
            git add docs/influenza_summary_updated.csv
            git add docs/agri_casa_summary_updated.csv
            git commit -m "Update CSV files"
            git push origin "$branch_name"
            git checkout main
            git merge --no-ff "$branch_name"
            git push origin main
            git branch -d "$branch_name"
            git push origin --delete "$branch_name"
          else
            echo "No changes in CSV files. Skipping commit and push."
          fi

      - name: Deploy applications
        env:
          influenza_token: ${{ secrets.INFLUENZA_TOKEN }}
          namru_biofire_token: ${{ secrets.NAMRU_BIOFIRE_TOKEN }}
          agri_casa_token: ${{ secrets.AGRI_CASA_TOKEN }}
          r_shiny_account_token: ${{ secrets.R_SHINY_ACCOUNT_TOKEN }}
        run: |
          Rscript code/deploy_app.R
