name: Update data weekly Monday 9am EST
on:
  schedule:
    - cron: "0 13 * * 1"
  push:
    branches: [ main ]

jobs:
    run_update_data:
      runs-on: ubuntu-latest
      defaults:
         run:
            shell: bash -el {0}
      steps:
         - uses: actions/checkout@v2
         - uses: mamba-org/setup-micromamba@v1

           with:
               environment-file: .github/Guatemala_env.yml
               environment-name: Guatemala_env
         - name: Run R file
           env:
             influenza_token: ${{ secrets.influenza_token }}
             namru_biofire_token: ${{ secrets.namru_biofire_token }}
             agri_casa_token: ${{ secrets.agri_casa_token }}
            run: |
             Rscript code/redcap_data_processing.R
